#!/usr/bin/env sh
. /etc/os-release

# Taken fron pfetch
if `xprop -version > /dev/null 2>&1` ; then
	id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
	id=${id##* }
	wm=$(xprop -id "$id" -notype -len 25 -f _NET_WM_NAME 8t)
	wm=${wm##*_NET_WM_NAME = \"}
	wm=${wm%%\"*}
fi

# Var Colors
GREEN='\033[32;01m'
YELLOW='\033[33;01m'
RED='\033[1;31m'
BLUE='\033[34;01m'
PURPLE='\033[35m'
NORMAL='\033[0m'

pkgs() {
  #[ -e "/usr/bin/pkgmanager" ] && pkgs="$PURPLE pkgs:$NORMAL $(command to count packages.)"
  [ -e "/usr/bin/emerge" ] && pkgs="$PURPLE pkgs:$NORMAL $(printf '%s\n' /var/db/pkg/*/*/ | wc -l)" # emerge portage
  [ -e "/usr/bin/pacman" ] && pkgs="$PURPLE pkgs:$NORMAL $(pacman -Q | wc -l)" # pacman
  [ -e "/usr/bin/apt" ] && pkgs="$PURPLE pkgs:$NORMAL $(dpkg --list | wc -l)" # apt dpkg
  [ -e "/usr/bin/rpm " ] && pkgs="$PURPLE pkgs:$NORMAL $(rpm -qa | wc -l)" # rpm dnf yum
  [ -e "/usr/bin/apk" ] && pkgs="$PURPLE pkgs:$NORMAL $(apk list | wc -l)" # apk
  [ -e "/usr/bin/xbps-query" ] && pkgs="$PURPLE pkgs:$NORMAL $(xbps-query -l | wc -l)" # xbps
  
}
pkgs

# Set USER and HOSTNAME for non-bash shells
: "${USER=$(id -un)}${HOSTNAME=$(uname -n)}"

# Structure Vars
host=" $PURPLE$USER$NORMAL@$BLUE$HOSTNAME$NORMAL"
chars=$(echo "$USER@$HOSTNAME" | wc -m)
# Draw line
line=''; i=0
while [ "$((i+=1))" -lt "$chars" ]; do
	line="${line}─"
done

# get a value between 1 and 2
randomv=$(shuf -i 1-2 -n 1)
os="$RED os:$NORMAL $PRETTY_NAME"
kernel="$BLUE kernel:$NORMAL $(uname -r)"
shell="$YELLOW shell:$NORMAL ${SHELL##*/}"
wm_name="$GREEN wm:$NORMAL ${wm:-none}"

if [ $randomv = 2 ];then
printf "%s %b\n" \
	"           " "$host" \
	"  __   __  " " $line" \
	" (  \,/  ) "  "$os" \
	"  \_ | _/  "  "$kernel" \
	"  (_/ \_)  " "$pkgs" \
	"           " "$shell" \
	"           " "$wm_name\n" \
	"" "Talking is$GREEN easy$NORMAL, show me the$RED code$NORMAL"
else
	printf "%s %b\n" \
	"           " "$host" \
	"   (\_/)   " " $line" \
	" __(. .)__ " "$os" \
	" \__|_|__/ " "$kernel" \
	"    / \    " "$pkgs" \
	"           " "$shell" \
	"           " "$wm_name\n" \
	"" "Talking is$GREEN easy$NORMAL, show me the$RED code$NORMAL"
fi

#pad="[13G"
#cat << EOF
#${pad}$BLUE$host
#   (\_/) ${pad}$NORMAL$line
# __(. .)__ ${pad}$PURPLE$os$NORMAL
# \__|_|__/ ${pad}$RED$kernel$NORMAL
#    / \ ${pad}$GREEN$shell$NORMAL
#${pad}$YELLOW$wm_name
#EOF

